# Site settings
title: Hello!
description: Modern-Blog A Elegant template for Jekyll
keywords: Coffee, Coding, Dinosaurs Rawrrr
author: Cheyenne Arrowsmith
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.alwayscheyenne.com" # the base hostname & protocol for your site
future: true
